version: "3.7"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  web:
    image: nginx:latest
    container_name: redirector
    volumes:
      - ./redirect.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=goodmc.ru,www.goodmc.ru
      - LETSENCRYPT_HOST=goodmc.ru,www.goodmc.ru
      - LETSENCRYPT_EMAIL=admin@goodmc.org
    restart: unless-stopped
